### ISSUE TITLE
Console Application error.

### ISSUE THREAD

**Issue by michieal** [GerjanVlot/BERT-ML.NET#9]
So, I updated this project (complete solution) to dotnet 6.0... The WebApi works, but the ConsoleApplication fails out with this error code:
```
/BERT-ML.NET-master/BERT.Console/bin/Debug/net6.0/BERT.Console "Bob is walking through the woods collecting blueberries and strawberries to make a pie." "What is his name?"
Unhandled exception. System.InvalidOperationException: Error initializing model :Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:InvalidProtobuf] Load model from Model/bertsquad-10.onnx failed:Protobuf parsing failed.
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options, PrePackedWeightsContainer prepackedWeightsContainer)
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options)
   at Microsoft.ML.Transforms.Onnx.OnnxModel..ctor(String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, Boolean ownModelFile, IDictionary`2 shapeDictionary, Int32 recursionLimit, Nullable`1 interOpNumThreads, Nullable`1 intraOpNumThreads)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)
 ---> Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:InvalidProtobuf] Load model from Model/bertsquad-10.onnx failed:Protobuf parsing failed.
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options, PrePackedWeightsContainer prepackedWeightsContainer)
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options)
   at Microsoft.ML.Transforms.Onnx.OnnxModel..ctor(String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, Boolean ownModelFile, IDictionary`2 shapeDictionary, Int32 recursionLimit, Nullable`1 interOpNumThreads, Nullable`1 intraOpNumThreads)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)
   --- End of inner exception stack trace ---
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, IDictionary`2 shapeDictionary, Int32 recursionLimit, Nullable`1 interOpNumThreads, Nullable`1 intraOpNumThreads)
   at Microsoft.ML.Transforms.Onnx.OnnxScoringEstimator..ctor(IHostEnvironment env, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, IDictionary`2 shapeDictionary, Int32 recursionLimit, Nullable`1 interOpNumThreads, Nullable`1 intraOpNumThreads)
   at Microsoft.ML.OnnxCatalog.ApplyOnnxModel(TransformsCatalog catalog, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu)
   at Microsoft.ML.Models.BERT.Onnx.OnnxModelConfigurator`1.SetupMlNetModel(IOnnxModel onnxModel) in /home/michieal/Desktop/Projects/projects/RiderProjects/BERT-ML.NET-master/Microsoft.ML.Models.BERT/Onnx/OnnxModelConfigurator.cs:line 25
   at Microsoft.ML.Models.BERT.Onnx.OnnxModelConfigurator`1..ctor(IOnnxModel onnxModel) in /home/michieal/Desktop/Projects/projects/RiderProjects/BERT-ML.NET-master/Microsoft.ML.Models.BERT/Onnx/OnnxModelConfigurator.cs:line 15
   at Microsoft.ML.Models.BERT.BertModel.Initialize() in /home/michieal/Desktop/Projects/projects/RiderProjects/BERT-ML.NET-master/Microsoft.ML.Models.BERT/BertModel.cs:line 30
   at BERT.Console.Program.Main(String[] args) in /home/michieal/Desktop/Projects/projects/RiderProjects/BERT-ML.NET-master/BERT.Console/Program.cs:line 18

Process finished with exit code 134.
```

I'm pretty curious as to how to fix this, as it should either work for both projects in the solution, or fail for both. Mind you, I had to download a new copy of the bert-squad 10 onnx model, as the one that the shell file grabbed was corrupt and only 137k, instead of ~400mb.

My use case: Learning about BERT models, and having it do Q&A's as a front end for a generative text AI Model. 

Any and all help with this is very much appreciated and TIA!!!

**Comment by Gigabyte0x1337** [comment]
I have upgraded the project to dotnet see the last commit. The error you mentioned is related to the model file indeed. You should manually download the model. I tested API and ConsoleApp on Linux (WSL) and Windows, and they both worked.

Sounds fun, BERT is a great way to get started with NLP because the model is simple to consume yet powerful. But if you want to build something with Q&A ChatGPT models are far better at that. https://platform.openai.com/docs/guides/chat for C# dotnet see https://www.nuget.org/packages/OpenAI/ of course depending on your specific use-case. 

This was just a fun project for me to make something simple with BERT Q&A that isn't as magical as the Python implementations. Learned a lot!
